// Copyright 2010 Google Inc. All Rights Reserved.
// Refactored from contributions of various authors in strings/strutil.h
//
// This file contains conversion functions from various data types to
// strings and back.

#pragma once

#include <cstring>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>

#include <glog/logging.h>

#include <cstdint>

#include <string_view>
#include "kudu/gutil/endian.h"
#include "kudu/gutil/int128.h"
#include "kudu/gutil/stl_util.h"
#include "kudu/gutil/type_traits.h"

// Converts a 4-byte uint32_t to a string such that the string keys sort in
// the same order as the original uint32_t value.
// TODO(user): Rework all reinterpret_casts<> in this file.
inline void keyFromUint32(uint32_t u32, std::string* key) {
  uint32_t norder = ghtonl(u32);
  key->assign(reinterpret_cast<const char*>(&norder), sizeof(norder));
}

// Converts "fp" to an 8-byte string key
inline void keyFromUint64(uint64_t fp, std::string* key) {
  uint64_t norder = htonll(fp);
  key->assign(reinterpret_cast<const char*>(&norder), sizeof(norder));
}

// Converts a 16-byte uint128 to a string such that the string keys sort in
// the same order as the original uint128 value.
inline void keyFromUint128(kudu::uint128 fp, std::string* key) {
  uint64_t norder[] = {htonll(Uint128High64(fp)), htonll(Uint128Low64(fp))};
  key->assign(reinterpret_cast<const char*>(norder), 2 * sizeof(norder[0]));
}

// This version of keyFromUint32 is less efficient but very convenient
std::string uint32ToKey(uint32_t u32);

// This version of keyFromUint64 is less efficient but very convenient
std::string uint64ToKey(uint64_t fp);

// This version of keyFromUint128 is less efficient but very convenient
std::string uint128ToKey(kudu::uint128 u128);

// Converts a 4-byte string key (typically generated by keyFromUint32 or
// uint32ToKey) into a uint32_t value.
inline uint32_t keyToUint32(std::string_view key) {
  uint32_t value;
  DCHECK_EQ(key.size(), sizeof(value));
  memcpy(&value, key.data(), sizeof(value));
  return gntohl(value);
}

// Converts an 8-byte string key (typically generated by uint64ToKey or
// keyFromUint64) into a uint64_t value
inline uint64_t keyToUint64(std::string_view key) {
  uint64_t value;
  DCHECK_EQ(key.size(), sizeof(value));
  memcpy(&value, key.data(), sizeof(value));
  return ntohll(value);
}

// Converts a 16-byte string key (typically generated by uint128ToKey or
// keyFromUint128) into a uint128 value
inline kudu::uint128 keyToUint128(std::string_view key) {
  uint64_t v0, v1;
  DCHECK_EQ(key.size(), sizeof(v0) + sizeof(v1));
  memcpy(&v0, key.data(), sizeof(v0));
  memcpy(&v1, key.data() + sizeof(v0), sizeof(v1));
  return kudu::uint128(ntohll(v0), ntohll(v1));
}

// Converts "i32" to a 4-byte string key
// NOTE: Lexicographic ordering of the resulting strings does not in
// general correspond to any natural ordering of the corresponding
// integers. For non-negative inputs, lexicographic ordering of the
// resulting strings corresponds to increasing ordering of the
// integers. However, negative inputs are sorted *after* the non-negative
// inputs. To obtain keys such that lexicographic ordering corresponds
// to the natural total order on the integers, use orderedStringFromInt32()
// or reverseOrderedStringFromInt32() instead.
void keyFromInt32(int32_t i32, std::string* key);

// Convenient form of keyFromInt32.
inline std::string int32ToKey(int32_t i32) {
  std::string s;
  keyFromInt32(i32, &s);
  return s;
}

// Converts a 4-byte string key (typically generated by keyFromInt32)
// into an int32_t value
int32_t keyToInt32(std::string_view key);

// Converts a double value to an 8-byte string key, so that
// the string keys sort in the same order as the original double values.
void keyFromDouble(double x, std::string* key);

// Converts key generated by keyFromDouble() back to double.
double keyToDouble(std::string_view key);

// This version of keyFromDouble is less efficient but very convenient
std::string doubleToKey(double x);

// Converts int32_t to a 4-byte string key such that lexicographic
// ordering of strings is equivalent to sorting in increasing order by
// integer values. This can be useful when constructing secondary
void orderedStringFromInt32(int32_t i32, std::string* key);

// This version of orderedStringFromInt32 is less efficient but very convenient
std::string int32ToOrderedString(int32_t i32);

// The inverse of the above function.
int32_t orderedStringToInt32(std::string_view key);

// Converts int64_t to an 8-byte string key such that lexicographic
// ordering of strings is equivalent to sorting in increasing order by
// integer values.
void orderedStringFromInt64(int64_t i64, std::string* key);

// This version of orderedStringFromInt64 is less efficient but very convenient
std::string int64ToOrderedString(int64_t i64);

// The inverse of the above function.
int64_t orderedStringToInt64(std::string_view key);

// Converts int32_t to a 4-byte string key such that lexicographic
// ordering of strings is equivalent to sorting in decreasing order
// by integer values. This can be useful when constructing secondary
void reverseOrderedStringFromInt32(int32_t i32, std::string* key);

// This version of reverseOrderedStringFromInt32 is less efficient but very
std::string int32ToReverseOrderedString(int32_t i32);

// The inverse of the above function.
int32_t reverseOrderedStringToInt32(std::string_view key);

// Converts int64_t to an 8-byte string key such that lexicographic
// ordering of strings is equivalent to sorting in decreasing order
// by integer values. This can be useful when constructing secondary
void reverseOrderedStringFromInt64(int64_t i64, std::string* key);

// This version of reverseOrderedStringFromInt64 is less efficient but very
std::string int64ToReverseOrderedString(int64_t i64);

// The inverse of the above function.
int64_t reverseOrderedStringToInt64(std::string_view key);

// Stores the bytes of a plain old data type value in a C++ string.
// Verifies the given data type is a POD and copies the bytes of the
// value into a newly created string.
//
// Can replace the use of encode*, and avoid the use of castings,
// or adding additional functions for each type.
// For example, use:
//   int32 i = 100;
//   string s = encodePod(i);
// in place of:
//   string s = encodeUint32(static_cast<uint32>(i));
template <typename T>
inline std::string encodePod(const T& value) {
  KENFORCE_POD(T);
  std::string s;
  stlStringResizeUninitialized(&s, sizeof(T));
  memcpy(s.data(), &value, sizeof(T));
  return s;
}

// Retrieves the bytes of a plain old data type value from a std::string_view.
// Verifies the given data type is a POD and copies the bytes of the
// value from the given string.
// Returns true if the operation succeeded.
// Note that other than the data length, no check is (or can be)
// done on the type of data stored in the string.
//
// Can replace the use of decode*, and avoid the use of castings,
// or adding additional functions for each type.
// For example, use:
//   int32 i = 100;
//   int32 j;
//   string s = encodePod(i);
//   CHECK(decodePod(s, &j));
// in place of:
//   string s = encodeUint32(static_cast<uint32>(i));
//   CHECK(decodesUint32(s, static_cast<uint32*>(&j)));
template <typename T>
inline bool decodePod(std::string_view str, T* result) {
  KENFORCE_POD(T);
  CHECK(result != NULL);
  if (sizeof(*result) != str.size()) {
    return false;
  }
  memcpy(result, str.data(), sizeof(T));
  return true;
}

// Stores the value bytes of a vector of plain old data type in a C++ string.
// Verifies the given data type is a POD and copies the bytes of each value
// in the vector into a newly created string.
template <typename T>
inline std::string encodeVectorPod(const std::vector<T>& vec) {
  KENFORCE_POD(T);
  std::string s;
  stlStringResizeUninitialized(&s, vec.size() * sizeof(T));
  typename std::vector<T>::const_iterator iter;
  char* ptr;
  for (iter = vec.begin(), ptr = s.data(); iter != vec.end();
       ++iter, ptr += sizeof(T)) {
    memcpy(ptr, &(*iter), sizeof(T));
  }
  return s;
}

// Reconstructs a vector of a plain old data type values from a C++ string.
// Verifies the given data type is a POD and copies the bytes of each value
// from the given string to the given vector.
// Returns true if the operation succeeded.
// Note that other than the data length, no check is (or can be)
// done on the type of data stored in the string.
template <typename T>
inline bool decodeVectorPod(const std::string& str, std::vector<T>* result) {
  KENFORCE_POD(T);
  CHECK(result != NULL);
  if (str.size() % sizeof(T) != 0) {
    return false;
  }
  result->clear();
  result->reserve(str.size() / sizeof(T));
  T value;
  const char* begin = str.data();
  const char* end = str.data() + str.size();
  for (const char* ptr = begin; ptr != end; ptr += sizeof(T)) {
    memcpy(&value, ptr, sizeof(T));
    result->push_back(value);
  }
  return true;
}

// ----------------------------------------------------------------------
// encodeDouble()
// encodeFloat()
// encodeUint32()
// encodeUint64()
// decodeDouble()
// decodeFloat()
// decodeUint32()
// decodeUint64()
//    The encode* functions store the bytes of ints, floats or doubles into the
//    data bytes of a C++ string.  The decode* functions perform the reverse
//    operations, but operate on a std::string_view rather than directly on a
//    C++ string.  They return true iff s contained the right number of bytes.
//
//    These may be preferred to naked calls to encodePod/decodePod since
//    they make the payload type explicit.
//    Note that these encodings are NOT endian-neutral.
// ----------------------------------------------------------------------
inline std::string encodeDouble(double d) {
  return encodePod(d);
}

inline std::string encodeFloat(float f) {
  return encodePod(f);
}

inline std::string encodeUint32(uint32_t i) {
  return encodePod(i);
}

inline std::string encodeUint64(uint64_t i) {
  return encodePod(i);
}

inline bool decodeDouble(std::string_view s, double* d) {
  return decodePod(s, d);
}

inline bool decodeFloat(std::string_view s, float* f) {
  return decodePod(s, f);
}

inline bool decodeUint32(std::string_view s, uint32_t* i) {
  return decodePod(s, i);
}

inline bool decodeUint64(std::string_view s, uint64_t* i) {
  return decodePod(s, i);
}

// -------------------------------------------------------------------------
// dictionaryParse
//   This routine parses a common dictionary format (key and value separated
//   by ':', entries separated by commas). This format is used for many
//   complex commandline flags. It is also used to encode dictionaries for
//   exporting them or writing them to a checkpoint. Returns a vector of
//   <key, value> pairs. Returns true if there if no error in parsing, false
//    otherwise.
// -------------------------------------------------------------------------
bool dictionaryParse(
    const std::string& encodedStr,
    std::vector<std::pair<std::string, std::string>>* items);

// --------------------------------------------------------------------------
// dictionaryInt32Encode
// dictionaryInt64Encode
// dictionaryDoubleEncode
// dictionaryInt32Decode
// dictionaryInt64Decode
// dictionaryDoubleDecode
//   Routines to serialize/unserialize simple dictionaries
//   (string->T hashmaps). These are useful for exporting, checkpointing etc
//   *Decode routines clear the input dictionary. They return true if there
//   was no error in decoding, false otherwise.
//   Note: these routines are not meant for use with very large dictionaries.
//   They are written for convenience and not efficiency.
// --------------------------------------------------------------------------
std::string dictionaryInt32Encode(
    const std::unordered_map<std::string, int32_t>* dictionary);
std::string dictionaryInt64Encode(
    const std::unordered_map<std::string, int64_t>* dictionary);
std::string dictionaryDoubleEncode(
    const std::unordered_map<std::string, double>* dictionary);

bool dictionaryInt32Decode(
    std::unordered_map<std::string, int32_t>* dictionary,
    const std::string& encodedStr);
bool dictionaryInt64Decode(
    std::unordered_map<std::string, int64_t>* dictionary,
    const std::string& encodedStr);
bool dictionaryDoubleDecode(
    std::unordered_map<std::string, double>* dictionary,
    const std::string& encodedStr);
