// Copyright 2003, Google Inc.  All rights reserved.

#include "kudu/gutil/strings/serialize.h"

#include <bit>
#include <cstdlib>
#include <string>
#include <string_view>
#include <unordered_map>
#include <utility>
#include <vector>

#include <cstdint>

#include <fmt/core.h>
#include "kudu/gutil/strings/join.h"
#include "kudu/gutil/strings/split.h"
#include "kudu/gutil/strtoint.h"

using kudu::uint128;
using std::make_pair;
using std::pair;
using std::string;
using std::unordered_map;
using std::vector;

// Convert a uint32_t to a 4-byte string.
string uint32ToKey(uint32_t u32) {
  string key;
  keyFromUint32(u32, &key);
  return key;
}

string uint64ToKey(uint64_t fp) {
  string key;
  keyFromUint64(fp, &key);
  return key;
}

// Convert a uint128 to a 16-byte string.
string uint128ToKey(uint128 u128) {
  string key;
  keyFromUint128(u128, &key);
  return key;
}

// Converts int32_t to a 4-byte string key
// NOTE: Lexicographic ordering of the resulting strings does not in
// general correspond to any natural ordering of the corresponding
// integers. For non-negative inputs, lexicographic ordering of the
// resulting strings corresponds to increasing ordering of the
// integers. However, negative inputs are sorted *after* the non-negative
// inputs. To obtain keys such that lexicographic ordering corresponds
// to the natural total order on the integers, use orderedStringFromInt32()
// or reverseOrderedStringFromInt32() instead.
void keyFromInt32(int32_t i32, string* key) {
  // TODO(user): Redefine using bit_cast<> and keyFromUint32()?
  key->resize(sizeof(i32));
  for (int i = sizeof(i32) - 1; i >= 0; --i) {
    (*key)[i] = i32 & 0xff;
    i32 = (i32 >> 8);
  }
}

// Converts a 4-byte string key (typically generated by keyFromInt32)
// into an int32_t value
int32_t keyToInt32(std::string_view key) {
  int32_t i32 = 0;
  CHECK_EQ(key.size(), sizeof(i32));
  for (size_t i = 0; i < sizeof(i32); ++i) {
    i32 = (i32 << 8) | static_cast<unsigned char>(key[i]);
  }
  return i32;
}

// Converts a double value to an 8-byte string key, so that
// the string keys sort in the same order as the original double values.
void keyFromDouble(double x, string* key) {
  uint64_t n = std::bit_cast<uint64_t>(x);
  // IEEE standard 754 floating point representation
  //   [sign-bit] [exponent] [mantissa]
  //
  // Let "a", "b" be two double values, and F(.) be following
  // transformation.  We have:
  //   If 0 < a < b:
  //     0x80000000ULL < uint64_t(F(a)) < uint64_t(F(b))
  //   If a == -0.0, b == +0.0:
  //     uint64_t(F(-0.0)) == uint64_t(F(+0.0)) = 0x80000000ULL
  //   If a < b < 0:
  //     uint64_t(F(a)) < uint64_t(F(b)) < 0x80000000ULL
  const uint64_t kSignBit = 1ULL << 63;
  if ((n & kSignBit) == 0) {
    n += kSignBit;
  } else {
    n = -n;
  }
  keyFromUint64(n, key);
}

// Version of keyFromDouble that returns the key.
string doubleToKey(double x) {
  string key;
  keyFromDouble(x, &key);
  return key;
}

// Converts key generated by keyFromDouble() back to double.
double keyToDouble(std::string_view key) {
  int64_t n = keyToUint64(key);
  if (n & (1ULL << 63)) {
    n -= (1ULL << 63);
  } else {
    n = -n;
  }
  return std::bit_cast<double>(n);
}

// Converts int32_t to a 4-byte string key such that lexicographic
// ordering of strings is equivalent to sorting in increasing order by
// integer values. This can be useful when constructing secondary
void orderedStringFromInt32(int32_t i32, string* key) {
  uint32_t ui32 = static_cast<uint32_t>(i32) ^ 0x80000000;
  key->resize(sizeof ui32);
  for (int i = (sizeof ui32) - 1; i >= 0; --i) {
    (*key)[i] = ui32 & 0xff;
    ui32 = (ui32 >> 8);
  }
}

string int32ToOrderedString(int32_t i32) {
  string key;
  orderedStringFromInt32(i32, &key);
  return key;
}

// The inverse of the above function.
int32_t orderedStringToInt32(std::string_view key) {
  uint32_t ui32 = 0;
  CHECK(key.size() == sizeof ui32);
  for (int i = 0; i < sizeof ui32; ++i) {
    ui32 = (ui32 << 8);
    ui32 = ui32 | static_cast<unsigned char>(key[i]);
  }
  return static_cast<int32_t>(ui32 ^ 0x80000000);
}

// Converts int64_t to a 8-byte string key such that lexicographic
// ordering of strings is equivalent to sorting in increasing order by
// integer values.
void orderedStringFromInt64(int64_t i64, string* key) {
  uint64_t ui64 = static_cast<uint64_t>(i64) ^ (1ULL << 63);
  key->resize(sizeof ui64);
  for (int i = (sizeof ui64) - 1; i >= 0; --i) {
    (*key)[i] = ui64 & 0xff;
    ui64 = (ui64 >> 8);
  }
}

string int64ToOrderedString(int64_t i64) {
  string key;
  orderedStringFromInt64(i64, &key);
  return key;
}

// The inverse of the above function.
int64_t orderedStringToInt64(std::string_view key) {
  uint64_t ui64 = 0;
  CHECK(key.size() == sizeof ui64);
  for (int i = 0; i < sizeof ui64; ++i) {
    ui64 = (ui64 << 8);
    ui64 = ui64 | static_cast<unsigned char>(key[i]);
  }
  return static_cast<int64_t>(ui64 ^ (1ULL << 63));
}

// Converts int32_t to a 4-byte string key such that lexicographic
// ordering of strings is equivalent to sorting in decreasing order
// by integer values. This can be useful when constructing secondary
void reverseOrderedStringFromInt32(int32_t i32, string* key) {
  // ~ is like -, but works even for INT_MIN. (-INT_MIN == INT_MIN,
  // but ~x = -x - 1, so ~INT_MIN = -INT_MIN - 1 = INT_MIN - 1 = INT_MAX).
  orderedStringFromInt32(~i32, key);
}

string int32ToReverseOrderedString(int32_t i32) {
  string key;
  reverseOrderedStringFromInt32(i32, &key);
  return key;
}

// The inverse of the above function.
int32_t reverseOrderedStringToInt32(std::string_view key) {
  return ~orderedStringToInt32(key);
}

// Converts int64_t to an 8-byte string key such that lexicographic
// ordering of strings is equivalent to sorting in decreasing order
// by integer values. This can be useful when constructing secondary
void reverseOrderedStringFromInt64(int64_t i64, string* key) {
  return orderedStringFromInt64(~i64, key);
}

string int64ToReverseOrderedString(int64_t i64) {
  string key;
  reverseOrderedStringFromInt64(i64, &key);
  return key;
}

// The inverse of the above function.
int64_t reverseOrderedStringToInt64(std::string_view key) {
  return ~orderedStringToInt64(key);
}

// --------------------------------------------------------------------------
// dictionaryInt32Encode
// dictionaryInt64Encode
// dictionaryDoubleEncode
// dictionaryInt32Decode
// dictionaryInt64Decode
// dictionaryDoubleDecode
//   Routines to serialize/unserialize simple dictionaries
//   (string->T hashmaps). We use ':' to separate keys and values,
//   and commas to separate entries.
// --------------------------------------------------------------------------

string dictionaryInt32Encode(const unordered_map<string, int32_t>* dictionary) {
  vector<string> entries;
  for (const auto& entry : *dictionary) {
    entries.push_back(fmt::format("{}:{}", entry.first, entry.second));
  }

  string result;
  JoinStrings(entries, ",", &result);
  return result;
}

string dictionaryInt64Encode(const unordered_map<string, int64_t>* dictionary) {
  vector<string> entries;
  for (const auto& entry : *dictionary) {
    entries.push_back(fmt::format("{}:{}", entry.first, entry.second));
  }

  string result;
  JoinStrings(entries, ",", &result);
  return result;
}

string dictionaryDoubleEncode(const unordered_map<string, double>* dictionary) {
  vector<string> entries;
  for (const auto& entry : *dictionary) {
    entries.push_back(fmt::format("{}:{:g}", entry.first, entry.second));
  }

  string result;
  JoinStrings(entries, ",", &result);
  return result;
}

bool dictionaryParse(
    const string& encodedStr,
    vector<pair<string, string>>* items) {
  vector<string> entries;
  SplitStringUsing(encodedStr, ",", &entries);
  for (const auto& entry : entries) {
    vector<string> fields;
    SplitStringAllowEmpty(entry, ":", &fields);
    if (fields.size() != 2) { // parsing error
      return false;
    }
    items->emplace_back(fields[0], fields[1]);
  }
  return true;
}

bool dictionaryInt32Decode(
    unordered_map<string, int32_t>* dictionary,
    const string& encodedStr) {
  vector<pair<string, string>> items;
  if (!dictionaryParse(encodedStr, &items)) {
    return false;
  }

  dictionary->clear();
  for (const auto& item : items) {
    char* error = nullptr;
    const int32_t value = strto32(item.second.c_str(), &error, 0);
    if (error == item.second.c_str() || *error != '\0') {
      // parsing error
      return false;
    }
    (*dictionary)[item.first] = value;
  }
  return true;
}

bool dictionaryInt64Decode(
    unordered_map<string, int64_t>* dictionary,
    const string& encodedStr) {
  vector<pair<string, string>> items;
  if (!dictionaryParse(encodedStr, &items)) {
    return false;
  }

  dictionary->clear();
  for (const auto& item : items) {
    char* error = nullptr;
    const int64_t value = strto64(item.second.c_str(), &error, 0);
    if (error == item.second.c_str() || *error != '\0') {
      // parsing error
      return false;
    }
    (*dictionary)[item.first] = value;
  }
  return true;
}

bool dictionaryDoubleDecode(
    unordered_map<string, double>* dictionary,
    const string& encodedStr) {
  vector<pair<string, string>> items;
  if (!dictionaryParse(encodedStr, &items)) {
    return false;
  }

  dictionary->clear();
  for (const auto& item : items) {
    char* error = nullptr;
    const double value = strtod(item.second.c_str(), &error);
    if (error == item.second.c_str() || *error != '\0') {
      // parsing error
      return false;
    }
    (*dictionary)[item.first] = value;
  }
  return true;
}
