// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

#pragma once

#include <cstdint>
#include <iosfwd>
#include <string>

namespace kudu {
class faststring;
class Slice;

// A transaction timestamp generated by a Clock.
class Timestamp {
 public:
  using ValType = uint64_t;

  Timestamp() : v_(kInvalidTimestamp.v_) {}

  explicit Timestamp(uint64_t val) : v_(val) {}

  // Decode a timestamp from the given input slice.
  // Mutates the slice to point after the decoded timestamp.
  // Returns true upon success.
  bool decodeFrom(Slice* input);

  // Encode the timestamp to the given buffer.
  void encodeTo(faststring* dst) const;

  // Returns -1 if this < other.
  // Returns 1 if this > other.
  // Returns 0 if this == other.
  int compareTo(const Timestamp& other) const;

  std::string toString() const;

  // Returns this Timestamp as an uint64_t
  uint64_t toUint64() const;

  // Sets this Timestamp from 'value'
  void fromUint64(uint64_t value);

  ValType value() const {
    return v_;
  }

  // An initial transaction timestamp, higher than min so that we can have
  // a Timestamp guaranteed to be lower than all generated timestamps.
  static const Timestamp kInitialTimestamp;

  // An invalid transaction timestamp -- Timestamp types initialize to this
  // variable.
  static const Timestamp kInvalidTimestamp;

  // The maximum timestamp.
  static const Timestamp kMax;

  // The minimum timestamp.
  static const Timestamp kMin;

 private:
  friend bool operator==(const Timestamp& lhs, const Timestamp& rhs);
  friend bool operator!=(const Timestamp& lhs, const Timestamp& rhs);
  friend bool operator<(const Timestamp& lhs, const Timestamp& rhs);
  friend bool operator<=(const Timestamp& lhs, const Timestamp& rhs);
  friend bool operator>(const Timestamp& lhs, const Timestamp& rhs);
  friend bool operator>=(const Timestamp& lhs, const Timestamp& rhs);

  ValType v_;
};

std::ostream& operator<<(std::ostream& o, const Timestamp& timestamp);

inline int Timestamp::compareTo(const Timestamp& other) const {
  if (v_ < other.v_) {
    return -1;
  } else if (v_ > other.v_) {
    return 1;
  }
  return 0;
}

inline bool operator==(const Timestamp& lhs, const Timestamp& rhs) {
  return lhs.v_ == rhs.v_;
}

inline bool operator!=(const Timestamp& lhs, const Timestamp& rhs) {
  return !(lhs.v_ == rhs.v_);
}

inline bool operator<(const Timestamp& lhs, const Timestamp& rhs) {
  return lhs.v_ < rhs.v_;
}

inline bool operator>(const Timestamp& lhs, const Timestamp& rhs) {
  return rhs < lhs;
}

inline bool operator<=(const Timestamp& lhs, const Timestamp& rhs) {
  return !(lhs > rhs);
}

inline bool operator>=(const Timestamp& lhs, const Timestamp& rhs) {
  return !(lhs < rhs);
}

} // namespace kudu
