// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
#ifndef KUDU_CFILE_COMPRESSION_CODEC_H
#define KUDU_CFILE_COMPRESSION_CODEC_H

#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include <glog/logging.h>
#include <snappy-stubs-public.h>

#include <folly/SpinLock.h>
#include <folly/Synchronized.h>

#include "kudu/util/compression/compression.pb.h"
#include "kudu/util/slice.h"
#include "kudu/util/status.h"

namespace kudu {

class CompressionCodec {
 public:
  CompressionCodec();
  virtual ~CompressionCodec();

  Status CompressWithStats(
      const Slice& input,
      uint8_t* compressed,
      size_t* compressedLength) {
    Status ret = Compress(input, compressed, compressedLength);
    ++totalCompressions_;
    if (ret.ok()) {
      totalBytesBeforeCompression_ += input.size();
      totalBytesAfterCompression_ += *compressedLength;
    } else {
      ++totalCompressionErrors_;
    }
    return ret;
  }

  // REQUIRES: "compressed" must point to an area of memory that is at
  // least "MaxCompressedLength(input_length)" bytes in length.
  //
  // Takes the data stored in "input[0..input_length]" and stores
  // it in the array pointed to by "compressed".
  //
  // returns the length of the compressed output.
  virtual Status Compress(
      const Slice& input,
      uint8_t* compressed,
      size_t* compressedLength) = 0;

  virtual Status Compress(
      const std::vector<Slice>& inputSlices,
      uint8_t* compressed,
      size_t* compressedLength) = 0;

  Status UncompressWithStats(
      const Slice& compressed,
      uint8_t* uncompressed,
      size_t uncompressedLength) {
    Status ret = Uncompress(compressed, uncompressed, uncompressedLength);
    ++totalDecompressions_;
    if (ret.ok()) {
      totalBytesBeforeDecompression_ += compressed.size();
      totalBytesAfterDecompression_ += uncompressedLength;
    } else {
      ++totalDecompressionErrors_;
    }
    return ret;
  }

  // Given data in "compressed[0..compressed_length-1]" generated by
  // calling the Compress routine, this routine stores the uncompressed data
  // to uncompressed[0..uncompressed_length-1]
  // returns false if the message is corrupted and could not be uncompressed
  virtual Status Uncompress(
      const Slice& compressed,
      uint8_t* uncompressed,
      size_t uncompressedLength) = 0;

  // Returns the maximal size of the compressed representation of
  // input data that is "sourceBytes" bytes in length.
  virtual size_t MaxCompressedLength(size_t sourceBytes) const = 0;

  // Returns a JSON which contains stats
  virtual std::string Stats() const;

  // Sets a compression dictionary
  virtual Status SetDictionary(const std::string& /*dict*/) {
    LOG(WARNING) << "Dictionary compression is not supported by "
                 << CompressionType_Name(type());
    return Status::OK();
  }

  // Returns dictionary if dictionary compression is used
  virtual std::string GetDictionary() const {
    return {};
  }

  // Sets compression level
  virtual Status SetCompressionLevel(int level) {
    compressionLevel_ = level;
    return Status::OK();
  }

  virtual int CompressionLevel() const {
    return compressionLevel_;
  }

  // Return the type of compression implemented by this codec.
  virtual CompressionType type() const = 0;

 protected:
  int compressionLevel_ = 0;

 private:
  // Stats
  uint64_t totalBytesBeforeCompression_ = 0;
  uint64_t totalBytesAfterCompression_ = 0;
  uint64_t totalCompressions_ = 0;
  uint64_t totalBytesBeforeDecompression_ = 0;
  uint64_t totalBytesAfterDecompression_ = 0;
  uint64_t totalDecompressions_ = 0;
  uint64_t totalCompressionErrors_ = 0;
  uint64_t totalDecompressionErrors_ = 0;

  DISALLOW_COPY_AND_ASSIGN(CompressionCodec);
  CompressionCodec(CompressionCodec&&) = delete;
  CompressionCodec& operator=(CompressionCodec&&) = delete;
};

/**
 * Manages global compression codec, dictionary and compression level
 *
 * This class is thread safe but contention is not expected. In the commit path
 * we rely on taking RaftConsensus::lock_ and PeerConsensusQueue::queue_lock_
 * while updating codec, dict, level etc. and also compression and decompression
 * using the codec
 */
class CompressionCodecManager {
 public:
  static Status getCodec(
      CompressionType type,
      std::shared_ptr<CompressionCodec>* codec);

  static Status getCodec(
      const std::string& type,
      std::shared_ptr<CompressionCodec>* codec) {
    return getCodec(getCodecType(type), codec);
  }

  static std::shared_ptr<CompressionCodec> getCurrentCodec() {
    return codecData.lock()->first;
  }

  static Status setCurrentCodec(CompressionType type);

  static Status setCurrentCodec(const std::string& type) {
    return setCurrentCodec(getCodecType(type));
  }

  static std::string getDictionary() {
    return codecData.lock()->second;
  }

  static Status setDictionary(const std::string& dict);

  static unsigned int getCurrentDictionaryId();

  static unsigned int getDictionaryId(const std::string& dict);

  static Status setCurrentCompressionLevel(int level);

  static CompressionType getCodecType(const std::string& name) {
    CompressionType type;
    if (!CompressionType_Parse(name, &type)) {
      LOG(WARNING) << "Unable to recognize the compression codec '" << name
                   << "' using no compression as default.";
      return NO_COMPRESSION;
    }
    return type;
  }

  static std::string getCodecName(CompressionType type) {
    return CompressionType_Name(type);
  }

 private:
  CompressionCodecManager() {}

  using CodecPtr = std::shared_ptr<CompressionCodec>;
  using CodecData = std::pair<CodecPtr, std::string>;
  static folly::Synchronized<CodecData, folly::SpinLock> codecData;
  static std::atomic_int level;

  DISALLOW_COPY_AND_ASSIGN(CompressionCodecManager);
  ~CompressionCodecManager() = delete;
  CompressionCodecManager(CompressionCodecManager&&) = delete;
  CompressionCodecManager& operator=(CompressionCodecManager&&) = delete;
};

} // namespace kudu
#endif
